[[headers]]
  for = "/*"
  [headers.values]
#    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
#    Cross-Origin-Embedder-Policy = "require-corp"
# no use in this unless using ffmpeg
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
